services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-private-ntwk

  web:
    build: .
    ports:
      - "80:80"
    command: ["sh", "./start.sh"]
    depends_on:
      - postgres_db
    networks:
      - my-private-ntwk

volumes:
  postgres_db:
    driver: local

networks:
  my-private-ntwk:
    external:
      name: my_recipe_ntwk
