# Generated by Django 5.1.1 on 2024-09-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArgumentEvaluations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Argument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idea", models.TextField()),
                ("evidence", models.TextField(null=True)),
                ("explanation", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_of_study", models.TextField()),
                ("essay", models.TextField()),
                ("reparagraphed_essay", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "personal_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.personalstatement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="argument",
            name="personal_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="modules.personalstatement",
            ),
        ),
        migrations.CreateModel(
            name="Relevance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_relevant", models.BooleanField()),
                ("reason", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specificity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_specific", models.BooleanField()),
                ("reason", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suitability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_interest", models.BooleanField()),
                ("has_interest_reason", models.TextField()),
                ("is_capable", models.BooleanField()),
                ("is_capable_reason", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
    ]
