# Generated by Django 5.1.1 on 2024-09-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_capability_interest_delete_suitability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aspiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_aspiration", models.BooleanField()),
                ("reason_has_aspiration", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContributionToCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_contribution_to_community", models.BooleanField()),
                ("reason_has_contribution_to_community", models.TextField()),
                ("will_contribute_to_community", models.BooleanField()),
                ("reason_will_contribute_to_community", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_leadership", models.BooleanField()),
                ("reason_has_leadership", models.TextField()),
                (
                    "argument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules.argument",
                    ),
                ),
            ],
        ),
    ]
