# Generated by Django 5.1.1 on 2024-09-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
