# Generated by Django 5.1.1 on 2024-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_aspiration_contributiontocommunity_leadership'),
        ('modules', '0003_remove_appuser_username'),
    ]

    operations = [
    ]
