# Generated by Django 5.1.1 on 2024-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_merge_20240920_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='default_username', max_length=50),
        ),
    ]
