# Generated by Django 5.1.1 on 2024-09-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_appuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwantedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_unwanted_language', models.BooleanField()),
                ('has_unwanted_language_reason', models.TextField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.argument')),
            ],
        ),
    ]
