# Generated by Django 5.1.1 on 2024-09-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0008_jardineargumentevaluations_comment_is_good"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppUser",
        ),
    ]
