# Generated by Django 5.1.1 on 2024-09-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0009_delete_appuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalcomment",
            old_name="personal_state",
            new_name="personal_statement",
        ),
    ]
