# Generated by Django 5.1.1 on 2024-09-23 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appuser_free_upload_count'),
        ('modules', '0010_rename_personal_state_generalcomment_personal_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalstatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalstatement',
            name='focus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalstatement',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalstatement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_statements', to='authentication.appuser'),
        ),
    ]
