# Generated by Django 5.1.1 on 2024-09-23 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_personalstatement_created_at_personalstatement_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalstatement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
