# Generated by Django 5.1.1 on 2024-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='free_upload_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
