# Generated by Django 5.1.1 on 2024-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_appuser_free_upload_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
